apps/stocks/urls.py
from django.urls import path, include

from .views import *
from .api.views import *

app_name = 'stocks'
urlpatterns = [
    # {% url('stocks:list') %}
    path('', stocks_list_view, name='list'),
    # {% url('stocks:api_list') %}
    path('api/', stocks_list_api_view, name='api_list'),
    path('<slug:name>/', include([
        # {% url('stocks:prices') stock.name %}
        path('', stock_prices_list_view, name='prices'),
        # {% url('stocks:prices_analytics') stock.name %}
        path('analytics/', stock_prices_analytics_view, name='prices_analytics'),
        # {% url('stocks:prices_delta') stock.name %}
        path('delta/', stock_prices_delta_view, name='prices_delta'),
        path('insider/', include([
            # {% url('stocks:insiders_list') stock.name %}
            path('', stock_insiders_list_view, name='insiders_list'),
            # {% url('stocks:insider_trades') stock.name, insider.slug %}
            path('<slug:slug>/', insider_trades_list_view, name='insider_trades')
        ]))
    ])),
    path('api/<slug:name>/', include([
        # {% url('stocks:api_prices') stock.name %}
        path('', stock_prices_list_api_view, name='api_prices'),
        # {% url('stocks:api_prices_analytics') stock.name %}
        path('analytics/', stock_prices_analytics_api_view, name='api_prices_analytics'),
        # {% url('stocks:api_prices_delta') stock.name %}
        path('delta/', stock_prices_delta_api_view, name='api_prices_delta'),
        path('insider/', include([
            # {% url('stocks:api_insiders_list') stock.name %}
            path('', stock_insiders_list_api_view, name='api_insiders_list'),
            # {% url('stocks:api_insider_trades') stock.name, insider.slug %}
            path('<slug:slug>/', insider_trades_list_api_view, name='api_insider_trades')
        ]))
    ])),
]

config/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.stocks.urls', namespace='stocks'))
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

apps/stocks/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse
from model_utils import Choices

from .querysets import PriceQuerySet, TradeQuerySet


class Stock(models.Model):
    name = models.CharField(
        max_length=10,
        unique=True
    )

    company_name = models.CharField(
        max_length=255,
        default='',
        blank=True
    )

    def __str__(self):
        return self.name.upper()

    def get_absolute_url(self):
        return reverse('stocks:prices', kwargs={'name': self.name})


class Price(models.Model):
    stock = models.ForeignKey(
        to=Stock,
        on_delete=models.CASCADE,
        related_name='prices'
    )

    date = models.DateTimeField()

    open = models.DecimalField(
        max_digits=12,
        decimal_places=3,
        default=0
    )

    high = models.DecimalField(
        max_digits=12,
        decimal_places=3,
        default=0
    )

    low = models.DecimalField(
        max_digits=12,
        decimal_places=3,
        default=0
    )

    close = models.DecimalField(
        max_digits=12,
        decimal_places=3,
        default=0
    )

    volume = models.IntegerField(
        default=0
    )

    objects = PriceQuerySet.as_manager()

    def __str__(self):
        return f'{self.stock.name} ({self.date.strftime("%m/%d/%Y")})'


class Insider(models.Model):
    full_name = models.CharField(
        max_length=255
    )

    slug = models.SlugField(
        max_length=255,
        unique=True
    )

    def __str__(self):
        return self.full_name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.full_name)
        super().save(*args, **kwargs)


class Relation(models.Model):
    POSITIONS = Choices(
        (0, 'OFFICER', 'Officer'),
        (1, 'DIRECTOR', 'Director'),
        (2, 'OTHER', 'Other')
    )

    position = models.PositiveSmallIntegerField(
        choices=POSITIONS,
        default=POSITIONS.OFFICER
    )

    stock = models.ForeignKey(
        to=Stock,
        on_delete=models.CASCADE
    )

    insider = models.ForeignKey(
        to=Insider,
        on_delete=models.CASCADE
    )

    def __str__(self):
        return f'{self.insider} {self.get_position_display()} of {self.stock.company_name}'

    class Meta:
        default_related_name = 'relations'


class Trade(models.Model):
    OWNER_TYPES = Choices(
        (0, 'DIRECT', 'direct'),
        (1, 'INDIRECT', 'indirect'),
    )

    insider_relation = models.ForeignKey(
        to=Relation,
        on_delete=models.CASCADE,
        related_name='trades'
    )

    last_date = models.DateField()

    transaction_type = models.CharField(
        max_length=255
    )

    owner_type = models.PositiveSmallIntegerField(
        choices=OWNER_TYPES,
        default=OWNER_TYPES.DIRECT
    )

    shares_traded = models.IntegerField(
        default=0
    )

    last_price = models.DecimalField(
        max_digits=12,
        decimal_places=4,
        null=True,
        blank=True
    )

    shares_held = models.IntegerField(
        default=0
    )

    objects = TradeQuerySet.as_manager()

    class Meta:
        ordering = ('last_date', 'insider_relation__insider__full_name')

apps/stocks/api/views.py
from django.http import Http404
from rest_framework.generics import ListAPIView

from ..models import Stock, Price, Trade
from .serializers import (StockSerializer, PriceSerializer, TradeSerializer,
                          InsiderTradesSerializer, PriceAnalyticsSerializer, PriceDeltaSerializer)

__all__ = (
    'stocks_list_api_view', 'stock_prices_list_api_view', 'stock_insiders_list_api_view',
    'insider_trades_list_api_view', 'stock_prices_analytics_api_view',
    'stock_prices_delta_api_view'
)


class StocksListAPIView(ListAPIView):
    serializer_class = StockSerializer
    queryset = Stock.objects.all()

stocks_list_api_view = StocksListAPIView.as_view()


class StockPricesListAPIView(ListAPIView):
    serializer_class = PriceSerializer
    queryset = Price.objects.all()
    lookup_field = 'stock__name'
    lookup_url_kwarg = 'name'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(**{self.lookup_field: self.kwargs[self.lookup_url_kwarg]})

stock_prices_list_api_view = StockPricesListAPIView.as_view()


class StockInsidersListAPIView(ListAPIView):
    serializer_class = TradeSerializer
    queryset = Trade.objects.all().reverse()
    lookup_field = 'insider_relation__stock__name'
    lookup_url_kwarg = 'name'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(**{self.lookup_field: self.kwargs[self.lookup_url_kwarg]})

stock_insiders_list_api_view = StockInsidersListAPIView.as_view()


class InsiderTradesListAPIView(StockInsidersListAPIView):
    serializer_class = InsiderTradesSerializer
    lookup_field = 'insider_relation__insider__slug'
    lookup_url_kwarg = 'slug'

insider_trades_list_api_view = InsiderTradesListAPIView.as_view()


class StockPricesAnalyticsAPIView(StockPricesListAPIView):
    serializer_class = PriceAnalyticsSerializer

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.get_delta_between_dates(self.request)

stock_prices_analytics_api_view = StockPricesAnalyticsAPIView.as_view()


class StockPricesDeltaAPIView(StockPricesListAPIView):
    serializer_class = PriceDeltaSerializer

    def get_queryset(self):
        if 'value' not in self.request.GET or 'type' not in self.request.GET:
            raise Http404('Value and type aren\'t specified')
        qs = super().get_queryset().reverse()
        return qs.get_prices_for_delta(self.request)

stock_prices_delta_api_view = StockPricesDeltaAPIView.as_view()

apps/stocks/views.py
from django.http import Http404
from django.views.generic import ListView
from django.views.generic.detail import SingleObjectMixin

from .models import Stock, Trade, Insider

__all__ = (
    'stocks_list_view', 'stock_prices_list_view', 'stock_insiders_list_view',
    'insider_trades_list_view', 'stock_prices_analytics_view', 'stock_prices_delta_view'
)


class StocksListView(ListView):
    model = Stock
    context_object_name = 'stocks'
    template_name = 'stocks/stocks_list.html'

stocks_list_view = StocksListView.as_view()


class StockPricesListView(SingleObjectMixin, ListView):
    template_name = 'stocks/stock_prices.html'
    queryset = Stock.objects.all()
    slug_field = 'name'
    slug_url_kwarg = 'name'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=self.queryset)
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        return self.object.prices.all()

stock_prices_list_view = StockPricesListView.as_view()


class StockInsidersListView(SingleObjectMixin, ListView):
    template_name = 'stocks/stock_insiders.html'
    queryset = Stock.objects.all()
    slug_field = 'name'
    slug_url_kwarg = 'name'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=self.queryset)
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        return Trade.objects.filter(insider_relation__stock=self.object).default().reverse()

stock_insiders_list_view = StockInsidersListView.as_view()


class InsiderTradesListView(SingleObjectMixin, ListView):
    template_name = 'stocks/insider_trades.html'
    queryset = Insider.objects.all()

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=self.queryset)
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        return Trade.objects.filter(insider_relation__insider=self.object).default().reverse()

insider_trades_list_view = InsiderTradesListView.as_view()


class StockPricesAnalyticsView(StockPricesListView):
    template_name = 'stocks/stock_prices_analytics.html'

    def get_object(self, queryset=None):
        if 'date_from' not in self.request.GET or 'date_to' not in self.request.GET:
            raise Http404('Dates aren\'t specified')
        return super().get_object(queryset)

    def get_queryset(self):
        qs = super().get_queryset().reverse()
        return qs.get_delta_between_dates(self.request)

stock_prices_analytics_view = StockPricesAnalyticsView.as_view()


class StockPricesDeltaView(StockPricesListView):
    template_name = 'stocks/stock_prices_delta.html'

    def get_object(self, queryset=None):
        if 'value' not in self.request.GET or 'type' not in self.request.GET:
            raise Http404('Value and type aren\'t specified')
        return super().get_object(queryset)

    def get_queryset(self):
        qs = super().get_queryset().reverse()
        return qs.get_prices_for_delta(self.request)

stock_prices_delta_view = StockPricesDeltaView.as_view()

apps/templates/stocks/insider_base.html
{% load humanize %}

<div class="row">
  <div class="col">
    {% block heading %}{% endblock heading %}
    <table class="table table-bordered table-hover table-striped table-sm">
      <thead class="thead-light">
        <tr>
          {% if page == 'insiders' %}
            <th scope="col">Insider</th>
          {% else %}
            <th scope="col">Company</th>
          {% endif %}
          <th scope="col">Relation</th>
          <th scope="col">Last Date</th>
          <th scope="col">Transaction Type</th>
          <th scope="col">OwnerType</th>
          <th scope="col">Shares Traded</th>
          <th scope="col">Last Price</th>
          <th scope="col">Shares Held</th>
        </tr>
      </thead>
      <tbody>
        {% for trade in object_list %}
          <tr>
            {% if page == 'insiders' %}
              <td><a href="{% url 'stocks:insider_trades' stock.name trade.insider_relation.insider.slug %}">{{ trade.insider_relation.insider }}</a></td>
            {% else %}
              <td><a href="{{ trade.insider_relation.stock.get_absolute_url }}">{{ trade.insider_relation.stock.company_name }}</a></td>
            {% endif %}
            <td>{{ trade.insider_relation.get_position_display }}</td>
            <td>{{ trade.last_date|date:"m/d/Y" }}</td>
            <td>{{ trade.transaction_type }}</td>
            <td>{{ trade.get_owner_type_display }}</td>
            <td>{{ trade.shares_traded|intcomma }}</td>
            <td>{% if trade.last_price %}{{ trade.last_price|intcomma }}{% endif %}</td>
            <td>{{ trade.shares_held|intcomma }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

apps/templates/stocks/insider_trades.html
{% extends 'base.html' %}

{% block title %}{{ block.super }} - {{ insider }} Insider Trades{% endblock title %}

{% block content %}

  {% block heading %}<h1>Insider Trades of {{ insider }}</h1>{% endblock heading %}
  {% include 'stocks/insider_base.html' %}

{% endblock content %}

apps/templates/stocks/stock_insiders.html
{% extends 'base.html' %}

{% block title %}{{ block.super }} - Insider Activity{% endblock title %}

{% block content %}

  {% block heading %}<h1>{{ stock }} Insider Activity</h1>{% endblock heading %}
  {% include 'stocks/insider_base.html' with page='insiders' %}

{% endblock content %}

apps/templates/stocks/stock_prices.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}{{ block.super }} - Historical Stock Prices{% endblock title %}

{% block content %}

  <div class="row">
    <div class="col">
      {% block heading %}<h1>{{ stock }} ${{ stock.prices.first.close|floatformat:"2" }}</h1>{% endblock heading %}
      <h6><a href="{% url 'stocks:insiders_list' stock.name %}">{{ stock }} Insider Activity</a></h6>
      <table class="table table-bordered table-hover table-striped table-sm">
        <thead class="thead-light">
          <tr>
            <th scope="col">Date</th>
            <th scope="col">Open</th>
            <th scope="col">High</th>
            <th scope="col">Low</th>
            <th scope="col">Close / Last</th>
            <th scope="col">Volume</th>
          </tr>
        </thead>
        <tbody>
          {% for price in object_list %}
            <tr>
              <td>{{ price.date|date:"m/d/Y" }}</td>
              <td>{{ price.open }}</td>
              <td>{{ price.high }}</td>
              <td>{{ price.low }}</td>
              <td>{{ price.close|floatformat:"2" }}</td>
              <td>{{ price.volume|intcomma }}</td>
            </tr>
          {% endfor %}
        </tbody>
        {% block delta %}{% endblock delta %}
      </table>
    </div>
  </div>

{% endblock content %}

apps/templates/stocks/stock_prices_analytics.html
{% extends 'stocks/stock_prices.html' %}
{% load humanize %}

{% block title %}{{ block.super }} - Historical Stock Prices Analytics{% endblock title %}

{% block content %}
  {{ block.super }}
{% endblock content %}

{% block heading %}
  <h1>{{ stock }} Analytics</h1>
{% endblock heading %}

{% block delta %}
    <thead class="thead-light">
      <tr>
        <th scope="col">Delta</th>
        <th scope="col">&#9651; Open</th>
        <th scope="col">&#9651; High</th>
        <th scope="col">&#9651; Low</th>
        <th scope="col">&#9651; Close / Last</th>
        <th scope="col">&#9651; Volume</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td class="hidden"></td>
        <td>{{ object_list.last.delta_open }}</td>
        <td>{{ object_list.last.delta_high }}</td>
        <td>{{ object_list.last.delta_low }}</td>
        <td>{{ object_list.last.delta_close }}</td>
        <td>{{ object_list.last.delta_volume|intcomma }}</td>
      </tr>
    </tbody>
{% endblock delta %}

apps/templates/stocks/stock_prices_delta.html
{% extends 'stocks/stock_prices.html' %}
{% load humanize %}

{% block title %}{{ block.super }} - Historical Stock Prices Analytics{% endblock title %}

{% block content %}
  {{ block.super }}
{% endblock content %}

{% block heading %}
  <h1>{{ stock }} Analytics</h1>
{% endblock heading %}

{% block delta %}
  <tbody>
    <tr>
      <td class="hidden">Absolute Delta</td>
      {% if request.GET.type == 'open' %}
        <td>{{ object_list.last.absolute_delta }}</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      {% elif request.GET.type == 'high' %}
        <td></td>
        <td>{{ object_list.last.absolute_delta }}</td>
        <td></td>
        <td></td>
        <td></td>
      {% elif request.GET.type == 'low' %}
        <td></td>
        <td></td>
        <td>{{ object_list.last.absolute_delta }}</td>
        <td></td>
        <td></td>
      {% elif request.GET.type == 'close' %}
        <td></td>
        <td></td>
        <td></td>
        <td>{{ object_list.last.absolute_delta }}</td>
        <td></td>
      {% endif %}
    </tr>
  </tbody>
{% endblock delta %}

apps/templates/stocks/stocks_list.html
{% extends 'base.html' %}

{% block title %}{{ block.super }} - Stocks List{% endblock title %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-8">
      <div class="tab-content" id="nav-tabContent">
        {% for stock in stocks %}
          <a href="{{ stock.get_absolute_url }}" class="list-group-item d-flex justify-content-between align-items-center">
            {{ stock }}
          </a>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock content %}